In [50]:
## Import stuff
import numpy as np
import pandas as pd

 # This is ass. 1
 ## focus is on intro to python and data analytics
 ### There are 5 tasks:
 1. Python Variables
 1. Python Strings
 1. Python Lists, Sets, Tuples, Dictionaries
 1. Python NumPy
 1. Python Pandas
 
 Im Jupiter-Notebook sollen die einzelnen Analyseschritte detailliert beschrieben werden.
	- Gehen Sie insbesondere auf auch die Art und Weise ein, wie
		- die Daten aufbereiten wurden,
		- welche Methoden verwendet wurden und
		- wie die einzelnen Erkenntnisse bzw. Ergebnisse zustande kommen. 
- Für die Bewertung der Aufgaben ist nicht nur das Ergebnis relevant, sondern auch die Beschreibung des von Ihnen verwendeten Wegs, sowie Präsentation der Ergebnisse (Lesbarkeit, Angabe der Aufgabenummer). 

## 1. Python Variables
1.1 Assign the values “silver” and “Audi” to variables “color” and “brand” respectively. Use both variables to print the following sentence: "This silver audi is my car".

1.2 Display the result of the following expression using variables for each number: (15+6)*7.

In [2]:
### 1.1 Assign the values “silver” and “Audi” to variables “color” and “brand” respectively. Use both variables to print the following sentence: "This silver audi is my car".
#### assigned the color and brand
color = "Silver"
brand = "Audi"
## printed the sentence, to lower the cases I use the lower method 

print("This", color.lower(),brand.lower(),"is my car")

This silver audi is my car


In [3]:
### 1.2 Display the result of the following expression using variables for each number: (15+6)*7.
#### (15+6)*7 equals 147, thus I use variabels for the first, second and third number. 
####To get rid of the spaces I use the sep parameter

first_nr = 1
second_nr = 4
third_nr = 7
print(first_nr,second_nr,third_nr,sep="")

147


In [4]:
(15+6)*7

147

<hr>

## 2. Python Strings

### 2.1 
Given the following string: text="The most popular programming languages are: Python,Java,JavaScript and C#"
a) Add a space after each comma and assign it to the variable text
b) Add the following string to the variable text and print it out: ", according to TIOBE Index and PYPL"
### 2.2
With the following string given:mystring = "THIS IS A STRING IN LOWER CASE. and this is a string in upper case"
Convert the string to the correct form: first sentence should be in lower case and the second sentence in upper case.
Display correct string

In [7]:
## 2.1a)
### "".1 Given the following string: 
text="The most popular programming languages are: Python,Java,JavaScript and C#" 
## a) Add a space after each comma and assign it to the variable text 
##The replace() method replaces a string with another string
print(text.replace(",",", "))

The most popular programming languages are: Python, Java, JavaScript and C#


In [8]:
## 2.1b) Add the following string to the variable text and print it out: ", according to TIOBE Index and PYPL"
text2 = ", according to TIOBE Index and PYPL"
print(text.replace(",",", ") + text2)

The most popular programming languages are: Python, Java, JavaScript and C#, according to TIOBE Index and PYPL


In [11]:
## 2.2 With the following string given:
mystring = "THIS IS A STRING IN LOWER CASE. and this is a string in upper case"
## Convert the string to the correct form: first sentence should be in lower case and the second sentence in upper case.
## Display correct string
## just using swapcase()	Swaps cases, lower case becomes upper case and vice versa
print(mystring.swapcase())

this is a string in lower case. AND THIS IS A STRING IN UPPER CASE


<hr>

3. Python Lists, Sets, Tuples, Dictionaries
3.1 - 3.4

In [16]:
## 3.1 With a list given:
ToDoList = ["homework", "shopping", "meeting"]
##a) Change “shopping” to “cooking”
index = ToDoList.index("shopping") # Find the index of 'shopping'
ToDoList[index] = "cooking" # Replace 'shopping' with 'cooking'
## b) Use the append() method to add “chores” to the list
ToDoList.append("chores")
print(ToDoList)

['homework', 'cooking', 'meeting', 'chores']


In [20]:
##3.2 Return a new set with all items from both sets.:
Sports1 = {"curling", "skating", "skiing"}
Sports2 = {"hockey", "luge", "short-track"}
Sports3 = Sports1.union(Sports2) ## using union operator
print(Sports3)

{'curling', 'luge', 'skating', 'hockey', 'skiing', 'short-track'}


In [41]:
###3.3 Create a tuple containing following elements: Germany, Korea, Spain, Japan, France
country_tuple = ("Germany", "Korea", "Spain", "Japan", "France")
#print(country_tuple)
## a) Use negative indexing to access fourth element of the tuple
print(country_tuple[-2])
## b) Use the range of indexes to print the first, third and fifth element of the tuple
print(country_tuple[0:1], country_tuple[2:3], country_tuple[4:5])
#or
print(country_tuple[0], country_tuple[2], country_tuple[4])
#or
print(country_tuple[0::2])

Japan
('Germany',) ('Spain',) ('France',)
Germany Spain France
('Germany', 'Spain', 'France')


In [45]:
## 3.4 The following dictionary is given:
ComputerScienceMA = {
"Name": "Computer Science (MA)",
"Type": "Master",
"Study Programm": "Fulltime",
"ECTS": "120",
"Degree": "Master of Science"
}
#a) Check that dictionary is NOT empty, using len() method
##print(len(ComputerScienceMA))
if len(ComputerScienceMA) > 0:
    print("The dictionary is not empty.")
else:
    print("The dictionary is empty.")
#b) Iterate through the key:value pairs of dictionary
for key, value in ComputerScienceMA.items():
    print(key + ": " + value)


The dictionary is not empty.
Name: Computer Science (MA)
Type: Master
Study Programm: Fulltime
ECTS: 120
Degree: Master of Science


## 4. Python NumPy
4.1 Create 3-D numpy array of lengths 4, 2, 3 along the three dimensions with random values.:
4.2 Given is the following 1D-Array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Copy the contents of the array "arr" to "arr2" so that even if the original array will be modified it won't affect the сontents of the copy (dublicated array).

In [47]:
##4.1 Create 3-D numpy array of lengths 4, 2, 3 along the three dimensions with random values:
array_3d = np.random.rand(4, 2, 3)
print(array_3d)

[[[0.25814616 0.79593867 0.69600311]
  [0.67342726 0.4283402  0.21071887]]

 [[0.2393525  0.36387477 0.80280622]
  [0.74837343 0.31908118 0.54067454]]

 [[0.35993157 0.85534146 0.30802158]
  [0.64401443 0.40245366 0.61954425]]

 [[0.01013363 0.73083545 0.58146074]
  [0.14341644 0.95958341 0.63342974]]]


In [49]:
## 4.2 Given is the following 1D-Array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

## Copy the contents of the array "arr" to "arr2"
##so that even if the original array will be modified it won't affect the сontents of the copy (dublicated array).
# Create a copy of the array
arr2 = arr.copy()
## testing a modification of the initial array and the behaviour of arr2
# Modify the original array
arr[0] = 10
# Print the original array and the copy
print("Original array modified:", arr)
print("Copy array:", arr2)

Original array modified: [10  2  3  4  5  6  7  8]
Copy array: [1 2 3 4 5 6 7 8]


## 5. Python Pandas
5.1 
5.2


In [53]:
## 5.1 Import all 3 provided Excel files (name.xlsx, land.xlsx and year.xlsx) using Pandas and combine them in one Dataframe.


# Read the Excel file into a pandas DataFrame
data_name = pd.read_excel("https://github.com/Ph1lippK/DAPy/blob/master/01%20Assignment%20Data-20230529/name.xlsx", engine='openpyxl')



# Print the DataFrame
print(data_name)



BadZipFile: File is not a zip file

In [ ]:
5.2 The following list of dictionaries given:
list_of_colleagues = [
{'Name': 'Mike' , 'Age': 42, 'role': "Support Technician"},
{'Name': 'James', 'Age': 32, 'role': "Project Manager"},
{'Name': 'Tamara', 'Age': 26, 'role': "Marketing specialist"},
{'Name': 'Samantha' , 'Age': 29, 'role': "Software Developer"},
{'Name': 'Alex' , 'Age': 31, 'role': "UX/UI Designer"},
]
Create a DataFrame from this list.